#release configuration
#Wed Mar 25 20:45:32 CET 2026
projectVersionPolicyId=default
remoteTagging=true
scm.commentPrefix=[skip ci] [maven-release-plugin]
completedPhase=map-release-versions
scm.url=scm\:git\:git@github.com\:Jahia/csp-editor.git
project.rel.org.foo.modules\:csp-editor=1.0.0
exec.additionalArguments=-P jahia-tomcat,jahia-releases-archetypes,jahia-derby-embedded,jahia-internal-repository,jahia-enterprise-releases,archetype,marketing-factory,jahia-releases,jahia-customer-support-repository
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
completionGoals=frontend\:yarn@sync-pom scm\:checkin@package-json
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify frontend\:yarn@sync-pom scm\:checkin@package-json
